name: zuramaru
version: 0.1.0.0
category: Simple
author: aiya000
maintainer: aiya000 <aiya000.develop@gmail.com>
copyright: aiya000
license: MIT
homepage: https://github.com/aiya000/eliningen

ghc-options:
    - -Wall
    - -Wno-name-shadowing
    - -Wno-unused-do-bind
    - -Wno-orphans
    - -fprint-potential-instances
    - -fprint-explicit-kinds

dependencies:
    - base >= 4.7 && < 5
    - cmdargs
    - containers
    - distributive
    - either
    - extensible-effects
    - extra
    - lens
    - megaparsec
    - mono-traversable
    - mtl
    - profunctors
    - readline
    - safe
    - safe-exceptions
    - template-haskell
    - text
    - text-show
    - throwable-exceptions
    - transformers
    - type-iso

# TODO: Can I alternate type-iso by lens ?
library:
  source-dirs: src

executables:
  maru:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: zuramaru

tests:
  maru-test:
    main: Tasty.hs
    source-dirs:
      - test
      - src
    dependencies:
      - doctest
      - silently
      - tasty
      - tasty-discover
      - tasty-hunit
