name: zuramaru
version: 0.1.0.0
category: Simple
author: aiya000
maintainer: aiya000 <aiya000.develop@gmail.com>
copyright: aiya000
license: MIT
homepage: https://github.com/aiya000/hs-zuramaru
description: A lisp dialect
synopsis: A lisp processor, An inline-lisp, in Haskell

ghc-options:
    - -Wall
    - -Wno-name-shadowing
    - -Wno-unused-do-bind
    - -Wno-orphans
    - -fprint-potential-instances
    - -fprint-explicit-kinds

dependencies:
    - base >= 4.7 && < 5
    - cmdargs
    - containers
    - distributive
    - either
    - extensible
    - extra
    - lens
    - megaparsec
    - mono-traversable
    - mtl
    - mwc-random
    - profunctors
    - readline
    - safe
    - safe-exceptions
    - singletons
    - string-qq
    - template-haskell
    - text
    - text-show
    - throwable-exceptions
    - transformers

library:
  source-dirs: src

executables:
  maru:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: zuramaru

tests:
  unit-test:
    main: DocTest.hs
    source-dirs:
      - test/doctest
      - src
    dependencies:
      - doctest
  integrate-test:
    main: Tasty.hs
    source-dirs:
      - test/tasty
      - src
    dependencies:
      - silently
      - tasty
      - tasty-discover
      - tasty-hunit
