resolver: lts-8.0
flags: {}
extra-package-dbs: []
packages:
  - '.'
  - location:
      git: https://github.com/aiya000/hs-throwable-exceptions.git
      commit: 6c377199d61c23c7c89a185c40327432790e3be8
extra-deps:
  - throwable-exceptions-0.1.0.7
