resolver: lts-8.0
flags: {}
extra-package-dbs: []
packages:
  - '.'
  - location:
      git: https://github.com/aiya000/hs-throwable-exceptions.git
      commit: bfc052b585134b9a0f7247ff744276da169016d2
extra-deps:
  - throwable-exceptions-0.1.0.7
